//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Alpha_Team.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oferta_academicaEntities : DbContext
    {
        public oferta_academicaEntities()
            : base("name=oferta_academicaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<institucion> institucion { get; set; }
        public virtual DbSet<institucion_carrera> institucion_carrera { get; set; }
        public virtual DbSet<periodo> periodo { get; set; }
        public virtual DbSet<profesor> profesor { get; set; }
        public virtual DbSet<profesor_telefono> profesor_telefono { get; set; }
        public virtual DbSet<tipo_identificacion> tipo_identificacion { get; set; }
    }
}
