//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Alpha_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class institucion_carrera
    {
        public int id { get; set; }
        public int institucion_id { get; set; }
        public int carrera_id { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual institucion institucion { get; set; }
    }
}
