//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Alpha_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor_telefono
    {
        public int id { get; set; }
        public string telefono { get; set; }
        public int profesor_id { get; set; }
    
        public virtual profesor profesor { get; set; }
    }
}
