//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Alpha_Team.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profesor()
        {
            this.carrera = new HashSet<carrera>();
            this.profesor_telefono = new HashSet<profesor_telefono>();
        }
    
        public int id { get; set; }
        public long identificacion { get; set; }
        public string email { get; set; }
        public string nombre_completo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public int tipo_identificacion_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrera> carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesor_telefono> profesor_telefono { get; set; }
        public virtual tipo_identificacion tipo_identificacion { get; set; }
    }
}
